apiVersion: everest.percona.com/v2alpha1
kind: Backup
metadata:
  name: my-pg-backup
spec:
  tool: pg-operator
  databaseCluster: my-pg-cluster
  storage:
    # backupStorage: my-backup-storage
    s3:
      bucket: my-pg-backup-bucket
      region: us-west-2
      endpoint: s3.amazonaws.com
      accessKeyID: my-access-key-id
      secretAccessKey: my-secret-access-key
status:
  phase: Ready
  storage:
    s3:
      bucket: my-pg-backup-bucket
      region: us-west-2
      endpoint: s3.amazonaws.com
      accessKeyID: my-access-key-id
      secretAccessKey: my-secret-access-key
