apiVersion: everest.percona.com/v2alpha1
kind: DatabaseCluster
metadata:
  name: psmdb-cluster
  namespace: everest
spec:
  engine: percona-server-mongodb-operator
  podSchedulingPolicy: my-psmdb-psp
  
  # ... additional fields defined in DatabaseClusterDefinition
  

  allowUnsafeConfigurations: true
  
  components:
    mongod:
      type: mongod
      version: 8.0.8-3
      replicas: 3
      storage:
        class: standard
        size: 10Gi
      resources:
        requests:
          cpu: 2
          memory: 8Gi
        limits:
          cpu: 2
          memory: 8Gi
      config: |
        ... component specific configuration ...
        
      # custom fields from DatabaseClusterDefinition
      sharding:
        enabled: true
        shards: 3
        configServers:
          replicas: 3
          
    backup:
      type: backup
      version: "" # uses default since unspecified
    
    monitoring:
      type: pmm
      version: "" # uses default since unspecified
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 500m
          memory: 2Gi
      
      # custom fields from DatabaseClusterDefinition
      serverHost: http://pmm-server:8080