apiVersion: everest.percona.com/v2alpha1
kind: DatabaseCluster
metadata:
  name: psmdb-cluster
  namespace: everest
spec:
  engine: percona-server-mongodb-operator
  params: # global params
    allowUnsafeFlags: true
  topology:
    type: sharded # if none, use the default
    params:       # topology specific params
      shards: 3
    components:
      mongod:
        version: 8.0.8-3
      backup: 
        version: 2.9.1
      monitoring:
        version: 2.9.1
    componentInstances:
      engine:
        replicas: 3
        storage:
          size: 10Gi
          class: standard
      proxy:
        replicas: 3
        service:
          exposeType: LoadBalancer
      configServer:
        replicas: 3
      backupAgent:
        replicas: 1
      monitoring:
        replicas: 1
        params:     # component specific params
          serverHost: pmm-server
          credentialSecretName: pmm-secret
