apiVersion: everest.percona.com/v2alpha1
kind: DatabaseCluster
metadata:
  name: psmdb-cluster
  namespace: everest
spec:
  extension: psmdb

  params: # global params
    allowUnsafeFlags: true
  topology:
    type: sharded # if none, use the default
    params:       # topology specific params
      shards: 3
    components:
      mongod:
        version: 8.0.8-3
      backup: 
        version: 2.9.1
      monitoring:
        version: 2.9.1
    componentInstances:
      engine:
        spec:
          replicas: 3
          storage:
            size: 10Gi
            class: standard
      proxy:
        spec:
          replicas: 3
          service:
            exposeType: LoadBalancer
      configServer:
        spec:
          replicas: 3
      backupAgent:
        spec:
          replicas: 1
      monitoring:
        preset: my-pmm-preset
        # spec may be provided along with preset,
        # in which case it overrides the presets.
        spec:
          serverHost: pmm-server-override
      
status:
  awaitingTasks:
  - type: restart-psmdb-cluster
    message: "Require of 'Restart' task to be run with CRVersion update"
    lastTransitionTime: "2025-09-03T12:00:00Z"
    params:
      updateCRVersion: true

  conditions:
  - type: Ready
    status: True
    reason: All components are healty and running
    lastTransitionTime: "2025-09-03T12:00:00Z"
