apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "adv-layout-repl"
spec:
  configuration:
    clusters:
      - name: adv
        layout:
          shardsCount: 4
          replicas:
            - templates:
                podTemplate: clickhouse:22.8
            - templates:
                podTemplate: clickhouse:23.3
            - templates:
                podTemplate: clickhouse:23.8

  templates:
    podTemplates:

      - name: clickhouse:22.8
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:22.8

      - name: clickhouse:23.3
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.3


      - name: clickhouse:23.8
        spec:
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.8
