apiVersion: everest.percona.com/v2alpha1
kind: DatabaseClusterDefinition
metadata:
  name: clickhouse-definition
spec:
  definitions:
    global:
      openAPIV3Schema: {}
    components:
      clickhouse:
        openAPIV3Schema: {}
        defaults:
          annotations:
            test-annot: "true"
          labels:
            test-label: "true"
          container:
            image: "clickhouse/clickhouse-server:23.8"
            name: clickhouse
      clickhouse-keeper:
        openAPIV3Schema: {}
        defaults:
          container:
            image: "clickhouse/clickhouse-keeper:23.8"
            name: clickhouse-keeper
---
apiVersion: everest.percona.com/v2alpha1
kind: DatabaseCluster
metadata:
  name: my-cool-ch
spec:
  plugin: clickhouse
  global: {}
  components:
  - name: chi
    type: clickhouse
    replicas: 1
    version: "23.8" # NOOP for now
    storage:
      size: 1Gi
    customSpec:
      zookeeper:
        nodes:
          - host: keeper-my-cool-ch-keeper
            port: 2181
  - name: chk
    type: clickhouse-keeper
    replicas: 1
    version: "23.8" # NOOP for now
    storage:
      size: 1Gi
