apiVersion: everest.percona.com/v2alpha1
kind: DatabaseEngine
metadata:
  name: percona-server-mongodb-operator
spec:
  # Refernce to the DBC controller that reconciles DBC of this engine type.
  controllorRef:
    apiVersion: apps/v1 kind: Deployment
    name: percona-server-mongodb-operator
    namespace: everest-system
  
  additionalFields:
    openAPIV3Schema:
      allowUnsafeFlags:
        type: boolean
      initImage:
        type: string

  # Defines a list of components for this engine.
  components:
    mongod:
      versions:
        - version: 6.0.19-16
          image: percona/percona-server-mongodb:6.0.19-16-multi
        - version: 6.0.21-18
          image: percona/percona-server-mongodb:6.0.21-18
        - version: 7.0.18-11
          image: percona/percona-server-mongodb:7.0.18-11
        - version: 8.0.4-1
          image: percona/percona-server-mongodb:8.0.4-1-multi
        - version: 8.0.8-3
          image: percona/percona-server-mongodb:8.0.8-3
          default: true
    
    backup:
      versions:
        - version: 2.9.1
          image: percona/percona-server-mongodb-backup:2.9.1

    pmm:
      additionalFields:
        openAPIV3Schema:
          serverHost:
            type: string
          credentialSecretName:
            type: string
      versions:
        - version: 2.44.1
          image: percona/pmm-server:2.44.1
  
  topologies:
    standard:
      componentInstances:
        engine:
          type: mongod
          defaults:
            replicas: 3
        backupAgent:
          type: backup
        monitoring: 
          type: pmm
          optional: true

    sharded:
      # Topology specific settings
      additionalFields:
        openAPIV3Schema:
          shards:
            type: integer
            default: 3
      componentInstances:
        engine:
          type: mongod
          defaults:
            replicas: 3
        proxy:
          type: mongod
        configServer:
          type: mongod
        backupAgent:
          type: backup
        monitoring: 
          type: pmm
          optional: true
