apiVersion: everest.percona.com/v2alpha1
kind: Provider
metadata:
  name: percona-server-mongodb-operator
spec:
  # Defines a list of component types for this provider.
  # Each component type has a list of versions and images. 
  componentTypes:
    mongod:
      versions:
        - version: 6.0.19-16
          image: percona/percona-server-mongodb:6.0.19-16-multi
        - version: 6.0.21-18
          image: percona/percona-server-mongodb:6.0.21-18
        - version: 7.0.18-11
          image: percona/percona-server-mongodb:7.0.18-11
        - version: 8.0.4-1
          image: percona/percona-server-mongodb:8.0.4-1-multi
        - version: 8.0.8-3
          image: percona/percona-server-mongodb:8.0.8-3
          default: true
    
    backup:
      versions:
        - version: 2.9.1
          image: percona/percona-server-mongodb-backup:2.9.1

    pmm:
      versions:
        - version: 2.44.1
          image: percona/pmm-server:2.44.1

  # Defines a list of components for this provider.
  # Each component has a type from componentTypes.
  # One or more components may specify the same component type.
  components:
    engine:
      type: mongod
    configServer:
      type: mongod
    proxy:
      type: mongod
    backupAgent:
      type: backup
    monitoring:
      type: pmm
      
  # Defines a list of topologies for this provider.
  # Each topology defines the components that are supported by that topology.
  topologies:
    standard:
      components:
        engine:
          defaults:
            replicas: 3
        backupAgent:
          optional: true
        monitoring:
          optional: true

    sharded:
      components:
        engine:
          defaults:
            replicas: 3
        proxy: {}
        configServer: {}
        backupAgent:
          optional: true
        monitoring: 
          optional: true
